project:
  type: website
  # build output goes to ../docs (so repo root has docs/)
  output-dir: ../docs
  render:
    - "*.qmd"

resources:
  - images/**
  - files/**

execute:
  freeze: auto

website:
  site-url: "https://kaniz461.github.io/kfatemaa/"
  search: true
  navbar:
    collapse-below: lg
    right:
      - href: index.qmd
        text: About
      - href: project.qmd
        text: Project
      - href: publication.qmd
        text: Publication
      - icon: github
        href: https://github.com/Kaniz461/kfatemaa
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
