project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"
  resources:
    - mysite/images/**

execute:
  freeze: auto

website:
  title: "KANIZ FATEMA"
  site-url: https://kaniz461.github.io/kfatemaa/
  search: true
  navbar:
    logo: images/kaniz_profile.jpg
    collapse-below: lg
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publication.qmd
        text: Publication
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/Kaniz461/kfatemaa
        aria-label: GitHub


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
